name: LubeLogger
description: Self-hosted, open-source, web-based vehicle maintenance and fuel mileage tracker
version: 1.6.8
slug: lubelogger
startup: application
boot: auto
arch:
  - amd64
ingress: true
ingress_panel: true
ingress_port: 443
ingress_entry: /
environment:
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_CULTURE: en_US
  LANG: en_US.UTF-8
  LUBELOGGER_USERDATA_DIRECTORY: /data/
  DOTNET_DataProtection__KeyRingPath: /data/keys
map:
  - data:rw
panel_icon: mdi:car-wrench
url: https://lubelogger.com/
